apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "shelly_exporter.fullname" . }}
  labels:
    {{- include "shelly_exporter.labels" . | nindent 4 }}
data:
    k8s-config.yaml: |
        listenAddress: :{{ .Values.service.port }}
        debug: {{ .Values.shelly_exporter.debug }}
        deviceUpdateInterval: {{ .Values.shelly_exporter.updateInterval }}
        devices:
        {{- range .Values.shelly_exporter.devices }}
        - host: {{ .host }}
        {{- if .username }}
          username: {{ .username }}
        {{- end }}
        {{- if .password }}
          password: {{ .password }}
        {{- end }}
        {{- end }}