name: Chart Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write

jobs:
  release:
    permissions:
      contents: write
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0

      - name: Install yq
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/local/bin/yq
          sudo chmod +x /usr/local/bin/yq
          yq --version

      # Extract the chart version from Chart.yaml
      - name: Read Chart Version
        id: read-chart-version
        run: |
          version=$(yq '.version' < charts/shelly-exporter/Chart.yaml)
          echo "chart_version=$version" >> $GITHUB_OUTPUT
          echo "owner=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Chart | Push
        uses: appany/helm-oci-chart-releaser@v0.4.2
        with:
          name: shelly-exporter
          repository: ${{ steps.read-chart-version.outputs.owner }}
          tag: ${{ steps.read-chart-version.outputs.chart_version }}
          registry: ghcr.io
          registry_username: ${{ steps.read-chart-version.outputs.owner }}
          registry_password: ${{ secrets.GITHUB_TOKEN }}
          update_dependencies: 'true' # Defaults to false