replicaCount: 1

image:
  repository: ghcr.io/supporterino/shelly_exporter
  pullPolicy: IfNotPresent
  tag: ""

# -- This is for the secretes for pulling an image from a private repository more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
imagePullSecrets: []

# -- This is to override the chart name.
nameOverride: ""
fullnameOverride: ""

shelly_exporter:
  # -- Enable or disable debug mode for the Shelly Exporter.
  debug: false
  # -- Interval (in seconds) at which the exporter updates device data.
  updateInterval: 30
  # -- List of Shelly devices to monitor.
  devices:
  # -- IP address of the Shelly device.
  - host: 1.2.3.4
    # username:
    # (Optional) Username for the Shelly device.
    # password:
    # (Optional) Password for the Shelly device.


# -- Configuration for the Prometheus ServiceMonitor
serviceMonitor:
  # -- Enable or disable the creation of a ServiceMonitor resource
  enabled: false
  # -- Namespace where the ServiceMonitor resource should be created. Defaults to Release.Namespace
  namespace: ''
  # -- Labels to add to the ServiceMonitor resource
  labels: {}
  # -- Interval at which metrics should be scraped
  interval: 30s
  # -- Timeout for scraping metrics
  scrapeTimeout: 30s
  # -- Path to scrape for metrics
  path: /metrics
  # -- Scheme to use for scraping metrics (http or https)
  scheme: http
  # -- TLS configuration for scraping metrics
  tlsConfig: {}
  # -- Relabeling rules for the scraped metrics
  relabelings: []
  # -- Relabeling rules for the metrics before ingestion
  metricRelabelings: []
  # -- Target labels to add to the scraped metrics
  targetLabels: []

serviceAccount:
  # -- Specifies whether a service account should be created
  create: true
  # -- Automatically mount a ServiceAccount's API credentials?
  automount: true
  # -- Annotations to add to the service account
  annotations: {}
  # -- The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 8080
  name: http

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http

# -- Additional volumes on the output Deployment definition.
volumes: []
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

# -- Additional volumeMounts on the output Deployment definition.
volumeMounts: []
# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true

nodeSelector: {}

tolerations: []

affinity: {}
